# Use this file to control the main attributes of the website

# You
name: Dan Bennett

# Title for your site as it will appear in google
# e.g. Resume, Curriculum Vitae, Work History
title: Curriculum Vitae for Dan Bennett

# SEO description
description: Digital CV for Dan Bennett.

# URL of this resume
url: 'http://cv.dan-bennett.me'

# URL of your personal website (make same as URL if you don't have one)
personal: 'http://www.dan-bennett.me'

# these should be pretty self-explanatory :-P
email: dan@dan-bennett.me
#twitter: philipithomas

# Show this in the footer
copyright: All rights reserved.

# What should the navigation be called?
navigation: navigation

# Google analytics ID: UA-XXXXX-X
analytics: 

# Jekyll assets gem
assets:
  dirname: assets
  baseurl: /assets/
  css_compressor: yui
  js_compressor: yui
  cachebust: hard
  cache: false
  gzip: nil # Cloudflare will do this
  sources:
    - _assets/javascripts
    - _assets/stylesheets

# Files in this repo that we don't want to go to the web
exclude: [
  'scss',
  '*.rb',
  '*.yml',
  'vendor',
  'Gemfile',
  'Gemfile.lock',
  '*.sh',
  'README.md',
  'LICENSE.md',
]

theme: jekyll-theme-minimal